sudo: required
services:
  - docker
before_install:
  - docker build -t thinkpiece/udemy-docker-frontend -f Dockerfile.dev .
script:
  - docker run thinkpiece/udemy-docker-frontend npm run test:ci
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-frontend"
  env: "DockerFrontend-env"
  bucket_name: "elasticbeanstalk-us-east-1-382230010946"
  bucket_path: "docker-frontend"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"